export const albumList = [
  {
    id: 1,
    title: "Chaves",
    genre: "Minimalista",
    price: 66.0,
    img: "./src/assets/img/1.jpg",
    band: "São Pedro",
  },
  {
    id: 2,
    title: "Cruz",
    genre: "Minimalista",
    price: 72.0,
    img: "./src/assets/img/2.jpg",
    band: "Jesus Cristo",
  },
  {
    id: 3,
    title: "Tu es Petrus",
    genre: "Estampada",
    price: 68.0,
    img: "./src/assets/img/3.jpg",
    band: "São Pedro",
  },
  {
    id: 4,
    title: "Padre Paulo Ricardo",
    genre: "Estampado",
    price: 75.0,
    img: "./src/assets/img/4.jpg",
  },
  {
    id: 5,
    title: "Keep Calm",
    genre: "Escrita",
    price: 40.0,
    img: "./src/assets/img/5.jpg",
    band: "Terço",
  },
  {
    id: 6,
    title: "Carlo Acutis",
    genre: "Estampada",
    price: 80.0,
    img: "./src/assets/img/6.jpg",
  },
  {
    id: 7,
    title: "Totus Tuus Mariae",
    genre: "Estampada",
    price: 85.0,
    img: "./src/assets/img/7.jpg",
    band: "Nossa Senhora",
  },
  {
    id: 8,
    title: "Medalha de São Bento",
    genre: "Minimalista",
    price: 88.0,
    img: "./src/assets/img/8.jpg",
    band: "São Bento",
  },
  {
    id: 9,
    title: "Dicionário",
    genre: "Escrita",
    price: 31.0,
    img: "./src/assets/img/9.jpg",
  },
  {
    id: 10,
    title: "São Padre Pio",
    genre: "Estampada",
    price: 79.0,
    img: "./src/assets/img/10.jpg",
  },
  {
    id: 11,
    title: "Ora pro nobis",
    genre: "Estampada",
    price: 82.0,
    img: "./src/assets/img/11.jpg",
    band: "São Pio V",
  },
  {
    id: 12,
    title: "Eucaristia",
    genre: "Minimalista",
    price: 76.0,
    img: "./src/assets/img/12.jpg",
    band: "Hóstia",
  },
  {
    id: 13,
    title: "Angelle Dominus",
    genre: "Estampada",
    price: 74.0,
    img: "./src/assets/img/13.jpg",
    band: "São Gabriel e Nossa Senhora",
  },
  {
    id: 14,
    title: "São Bento",
    genre: "Estampada",
    price: 67.0,
    img: "./src/assets/img/14.jpg",
  },
  {
    id: 15,
    title: "In Persona Christ",
    genre: "Estampada",
    price: 63.0,
    img: "./src/assets/img/15.jpg",
    band: "Jesus and Priest",
  },
];

export const genresList = [
  "Todos",
  "Minimalista",
  "Estampada",
  "Escrita",
];